# See https://github.com/SpaceManiac/SpacemanDMM/blob/master/CONFIGURING.md for options

[display]
error_level = "hints"

[code_standards]
disallow_relative_type_definitions = false
disallow_relative_proc_definitions = false

[langserver]
dreamchecker = true

[debugger]
engine = "auxtools"

[diagnostics]
var_in_proc_parameter = "hint"
redefined_proc = "warning"
